package main

import (
	"fmt"
	"log"
	"net/http"

	js "github.com/TimLai666/go-vdom/jsdsl"
	. "github.com/TimLai666/go-vdom/vdom"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")

		doc := Document(
			"Do/AsyncDo 參數示例",
			[]LinkInfo{
				{Rel: "stylesheet", Href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"},
			},
			nil,
			nil,

			Div(Props{"class": "container mt-5"},
				H1(Props{"class": "mb-4"}, "Do/AsyncDo 參數使用示例"),
				P(Props{"class": "lead"}, "展示如何在 Do() 和 AsyncDo() 中使用參數"),

				Hr(),

				// 1. Do() 無參數（最常見）
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "1. Do() - 無參數"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "最常見的用法：直接執行代碼塊，不接收參數"),
							Pre(Props{"class": "bg-light p-3 rounded"},
								Code(`Button(Props{
	    "onClick": js.Do(nil,
	        js.Alert("'Hello!'"),
	    ),
	}, "Click")`),
							),
							Button(Props{
								"class": "btn btn-primary",
								"onClick": js.Do(nil,
									js.Alert("'Hello from Do without params!'"),
								),
							}, "測試無參數 Do"),
						),
					),
				),

				// 2. Do() 使用 event 參數
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "2. Do() - 使用 event 參數"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "在事件處理器中使用 event 對象時，必須聲明為參數"),
							Pre(Props{"class": "bg-light p-3 rounded"},
								Code(`Button(Props{
	    "onClick": js.Do([]string{"event"},
	        js.CallMethod("event", "preventDefault"),
	        js.Const("target", "event.target"),
	        js.Log("'Button clicked:', target"),
	    ),
	}, "Click")`),
							),
							Button(Props{
								"id":    "eventBtn",
								"class": "btn btn-success",
								"onClick": js.Do([]string{"event"},
									js.Const("target", "event.target"),
									js.Const("btnText", "target.textContent"),
									js.Alert("'你點擊了按鈕: ' + btnText"),
								),
							}, "測試 event 對象"),
							Div(Props{"class": "alert alert-info mt-3"},
								Strong("提示："), " 在 IIFE 中使用 event 對象時，必須將其聲明為參數並傳遞。",
							),
						),
					),
				),

				// 3. Do() 使用自定義參數（較少見）
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "3. Do() - 自定義參數（進階）"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "可以定義自定義參數，但在事件處理器中較少使用"),
							Pre(Props{"class": "bg-light p-3 rounded"},
								Code(`Button(Props{
    "onClick": js.Do(nil,[]string{"evt", "customArg"},
        js.CallMethod("evt", "preventDefault"),
        js.Log("'Custom arg:', customArg"),
    ),
}, "Click")`),
							),
							Div(Props{"class": "alert alert-warning"},
								Strong("注意："), " 在 onClick 等事件處理器中，自定義參數通常不會被傳入。",
								" 這個功能主要用於定義可重用的函數，而非直接用在事件處理器上。",
							),
						),
					),
				),

				// 4. AsyncDo() 無參數
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "4. AsyncDo() - 無參數"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "異步操作的標準用法"),
							Pre(Props{"class": "bg-light p-3 rounded"},
								Code(`Button(Props{
	    "onClick": js.AsyncDo(nil,
	        js.Const("response", "await fetch('/api')"),
	        js.Alert("'Done!'"),
	    ),
	}, "Load")`),
							),
							Button(Props{
								"class": "btn btn-info mb-3",
								"onClick": js.AsyncDo(nil,
									js.Alert("'開始異步操作...'"),
									JSAction{Code: "await new Promise(r => setTimeout(r, 1000))"},
									js.Alert("'異步操作完成！'"),
								),
							}, "測試異步操作（1秒延遲）"),
						),
					),
				),

				// 5. AsyncDo() 使用 event 參數
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "5. AsyncDo() - 使用 event 參數"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "在異步事件處理器中使用 event 對象，也需要聲明參數"),
							Pre(Props{"class": "bg-light p-3 rounded"},
								Code(`Button(Props{
	    "onClick": js.AsyncDo([]string{"event"},
	        js.Const("btnId", "event.target.id"),
	        js.Log("'Button ID:', btnId"),
	        JSAction{Code: "await someAsyncOperation()"},
	    ),
	}, "Async Click")`),
							),
							Button(Props{
								"id":    "asyncEventBtn",
								"class": "btn btn-warning mb-3",
								"onClick": js.AsyncDo([]string{"event"},
									js.Const("btnId", "event.target.id"),
									js.Const("btnClass", "event.target.className"),
									js.Alert("'按鈕 ID: ' + btnId"),
									JSAction{Code: "await new Promise(r => setTimeout(r, 500))"},
									js.Alert("'按鈕 class: ' + btnClass"),
								),
							}, "測試異步 + event"),
						),
					),
				),

				// 6. 實際應用：表單處理
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "6. 實際應用 - 表單處理"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "在表單提交中使用 event.preventDefault()"),
							Form(Props{
								"id": "testForm",
								"onSubmit": js.Do([]string{"event"},
									js.CallMethod("event", "preventDefault"),
									js.Const("formData", "new FormData(event.target)"),
									js.Const("name", "formData.get('name')"),
									js.Const("email", "formData.get('email')"),
									js.Alert("'提交表單！\\n姓名: ' + name + '\\n郵箱: ' + email"),
								),
							},
								Div(Props{"class": "mb-3"},
									Label(Props{"class": "form-label", "for": "name"}, "姓名："),
									Input(Props{
										"type":  "text",
										"class": "form-control",
										"id":    "name",
										"name":  "name",
										"value": "張三",
									}),
								),
								Div(Props{"class": "mb-3"},
									Label(Props{"class": "form-label", "for": "email"}, "郵箱："),
									Input(Props{
										"type":  "email",
										"class": "form-control",
										"id":    "email",
										"name":  "email",
										"value": "zhangsan@example.com",
									}),
								),
								Button(Props{
									"type":  "submit",
									"class": "btn btn-primary",
								}, "提交表單"),
							),
						),
					),
				),

				// 7. 實際應用：輸入處理
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "7. 實際應用 - 即時輸入處理"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "監聽輸入框變化並即時顯示"),
							Div(Props{"class": "mb-3"},
								Label(Props{"class": "form-label"}, "輸入文字："),
								Input(Props{
									"type":  "text",
									"class": "form-control",
									"id":    "liveInput",
									"onInput": js.Do([]string{"event"},
										js.Const("value", "event.target.value"),
										js.Const("length", "value.length"),
										JSAction{Code: "document.getElementById('liveOutput').textContent = value"},
										JSAction{Code: "document.getElementById('charCount').textContent = length + ' 字符'"},
									),
								}),
							),
							Div(Props{"class": "alert alert-info"},
								Div(Props{"id": "liveOutput", "class": "fw-bold"}, "你輸入的內容會即時顯示在這裡..."),
								Div(Props{"id": "charCount", "class": "text-muted small mt-2"}, "0 字符"),
							),
						),
					),
				),

				// 8. 實際應用：選擇框處理
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "8. 實際應用 - 選擇框處理"),
					Div(Props{"class": "card"},
						Div(Props{"class": "card-body"},
							P(Props{"class": "text-muted"}, "監聽選擇框變化"),
							Div(Props{"class": "mb-3"},
								Label(Props{"class": "form-label"}, "選擇你喜歡的顏色："),
								Select(Props{
									"class": "form-select",
									"onChange": js.Do([]string{"event"},
										js.Const("selectedValue", "event.target.value"),
										js.Const("selectedText", "event.target.options[event.target.selectedIndex].text"),
										JSAction{Code: "document.getElementById('colorPreview').style.backgroundColor = selectedValue"},
										JSAction{Code: "document.getElementById('colorName').textContent = '你選擇了：' + selectedText"},
									),
								},
									Option(Props{"value": ""}, "請選擇..."),
									Option(Props{"value": "#ff6b6b"}, "紅色"),
									Option(Props{"value": "#4ecdc4"}, "青色"),
									Option(Props{"value": "#45b7d1"}, "藍色"),
									Option(Props{"value": "#96ceb4"}, "綠色"),
									Option(Props{"value": "#ffeaa7"}, "黃色"),
									Option(Props{"value": "#dfe6e9"}, "灰色"),
								),
							),
							Div(Props{
								"id":    "colorPreview",
								"class": "border rounded p-4 mb-2",
								"style": "min-height: 100px; transition: background-color 0.3s;",
							}),
							Div(Props{
								"id":    "colorName",
								"class": "text-center text-muted",
							}, "請選擇一個顏色"),
						),
					),
				),

				// 總結
				Section(Props{"class": "mb-5"},
					H2(Props{"class": "mb-3"}, "✅ 使用指南"),
					Div(Props{"class": "row"},
						Div(Props{"class": "col-md-6"},
							Div(Props{"class": "card h-100 border-success"},
								Div(Props{"class": "card-header bg-success text-white"},
									H5(Props{"class": "mb-0"}, "推薦用法"),
								),
								Div(Props{"class": "card-body"},
									H6("Do() / AsyncDo() 無參數："),
									Ul(
										Li("用於不需要 event 對象的簡單操作"),
										Li("如 alert、console.log、簡單 DOM 操作"),
										Li("不涉及 event 對象時使用"),
									),
									Pre(Props{"class": "bg-light p-2 rounded small"},
										Code(`js.Do(nil,
    js.Alert("'Hello!'"),
    js.Log("'No event needed'"),
)`),
									),
								),
							),
						),
						Div(Props{"class": "col-md-6"},
							Div(Props{"class": "card h-100 border-warning"},
								Div(Props{"class": "card-header bg-warning"},
									H5(Props{"class": "mb-0"}, "進階用法"),
								),
								Div(Props{"class": "card-body"},
									H6("Do() / AsyncDo() 帶參數："),
									Ul(
										Li("需要使用 event 對象時必須聲明"),
										Li(Strong("事件處理器中使用 event 必須聲明參數")),
										Li("表單提交、輸入變化等都需要 event"),
									),
									Pre(Props{"class": "bg-light p-2 rounded small"},
										Code(`js.Do([]string{"event"},
    js.Const("val", "event.target.value"),
    js.Alert("val"),
)`),
									),
								),
							),
						),
					),
				),

				Section(Props{"class": "mb-5"},
					Div(Props{"class": "alert alert-info"},
						H5("💡 關鍵要點："),
						Ul(Props{"class": "mb-0"},
							Li(Strong("Do()"), " 用於同步操作"),
							Li(Strong("AsyncDo()"), " 用於異步操作（可使用 await）"),
							Li(Strong("重要"), "：使用 ", Code("event"), " 對象時必須聲明參數：", Code("[]string{\"event\"}")),
							Li("不使用 event 時傳 ", Code("nil")),
							Li("IIFE 會創建新作用域，event 必須顯式傳遞"),
						),
					),
				),
			),
		)

		fmt.Fprint(w, Render(doc))
	})

	port := ":8090"
	fmt.Printf("Do/AsyncDo 參數示例服務器已啟動，請訪問 http://localhost%s\n", port)
	log.Fatal(http.ListenAndServe(port, nil))
}
